### ISSUE TITLE
Import fails after pip install: from flask_swagger_ui import get_swaggerui_blueprint

### ISSUE THREAD

**Issue by mgardnerpsu** [sveint/flask-swagger-ui#1] opened 2017-01-06 15:44 UTC
I think the import needs to be removed from the `flask_swagger_ui/__init__.py` file - this works from context of `example.py` , but not after pip installation into site-packages

**Comment by sveint** [comment] 2017-02-07 12:50
Sorry for late reply!

I cannot reproduce this. Tried a clean virtualenv, pip installed the package and tried to import using `from flask_swagger_ui import get_swaggerui_blueprint` which works fine.

The line in the `__init__.py` exists to expose the function `get_swaggerui_blueprint` from the module `flask_swagger_ui` on the package level, basically letting you write `from flask_swagger_ui import get_swaggerui_blueprint` instead of `from flask_swagger_ui.flask_swagger_ui import get_swaggerui_blueprint`.

Please let me know if I misunderstood something.

**Comment by alde** [comment] 2017-02-21 13:40
I have the same issue, which led me to fork it and move everything into the __init__.py file, othewise using it with tox wouldn't work

**Comment by rredkovich** [comment] 2017-02-23 16:04
Have same issue with import on python3, hovewer successfully resolved after adding relative import in module `__init__.py`

```python
from .flask_swagger_ui import get_swaggerui_blueprint
```

**Comment by ffleandro** [comment] 2017-03-02 14:23
have the same problem using python `3.5.1`, solved using @rredkovich solution.

**Comment by sveint** [comment] 2017-03-03 09:44
Thanks!

I should of course have used relative imports (even though I use python2 still, so I didn't notice). I have committed the fix, will push to pypi shortly.

**Closed by sveint** 2017-03-03 09:44 UTC
